import type { Connector, Wire } from './types'

/**
 * Sample harness: J1–J2 power + two twisted shielded pairs under overall CAB1,
 * then ENABLE; J1–J3 sensor cable with pair shield. Pin order keeps each
 * cable's conductors contiguous so routing and shields stay clean.
 */
export const SAMPLE_CONNECTORS: Connector[] = [
  {
    connector_id: 'J2',
    connector_name: 'Battery / PDU',
    pin_count: 7,
    position_x: 48,
    position_y: 60,
  },
  {
    connector_id: 'J1',
    connector_name: 'Motor Controller',
    pin_count: 10,
    position_x: 520,
    position_y: 60,
  },
  {
    connector_id: 'J3',
    connector_name: 'Sensor',
    pin_count: 4,
    position_x: 1000,
    position_y: 200,
  },
]

export const SAMPLE_WIRES: Wire[] = [
  {
    wire_id: 'W1',
    from_connector: 'J2',
    from_pin: '1',
    to_connector: 'J1',
    to_pin: '1',
    wire_color: 'red',
    gauge: '16 AWG',
    signal_name: '+24V',
  },
  {
    wire_id: 'W2',
    from_connector: 'J2',
    from_pin: '2',
    to_connector: 'J1',
    to_pin: '2',
    wire_color: 'black',
    gauge: '16 AWG',
    signal_name: 'GND',
  },
  {
    wire_id: 'W3',
    from_connector: 'J1',
    from_pin: '3',
    to_connector: 'J2',
    to_pin: '3',
    wire_color: 'yellow',
    gauge: '22 AWG',
    signal_name: 'CAN_H',
    twist_group: 'CAN',
    shield_group: 'CAN',
    overall_shield: 'CAB1',
  },
  {
    wire_id: 'W4',
    from_connector: 'J1',
    from_pin: '4',
    to_connector: 'J2',
    to_pin: '4',
    wire_color: 'green',
    gauge: '22 AWG',
    signal_name: 'CAN_L',
    twist_group: 'CAN',
    shield_group: 'CAN',
    overall_shield: 'CAB1',
  },
  {
    wire_id: 'W5',
    from_connector: 'J1',
    from_pin: '5',
    to_connector: 'J2',
    to_pin: '5',
    wire_color: 'orange',
    gauge: '22 AWG',
    signal_name: 'ENC_A',
    twist_group: 'ENC',
    shield_group: 'ENC',
    overall_shield: 'CAB1',
  },
  {
    wire_id: 'W6',
    from_connector: 'J1',
    from_pin: '6',
    to_connector: 'J2',
    to_pin: '6',
    wire_color: 'violet',
    gauge: '22 AWG',
    signal_name: 'ENC_B',
    twist_group: 'ENC',
    shield_group: 'ENC',
    overall_shield: 'CAB1',
  },
  {
    wire_id: 'W7',
    from_connector: 'J1',
    from_pin: '7',
    to_connector: 'J2',
    to_pin: '7',
    wire_color: 'blue',
    gauge: '22 AWG',
    signal_name: 'ENABLE',
  },
  {
    wire_id: 'W8',
    from_connector: 'J1',
    from_pin: '8',
    to_connector: 'J3',
    to_pin: '1',
    wire_color: 'white',
    gauge: '24 AWG',
    signal_name: 'SIG+',
    twist_group: 'SENS',
    shield_group: 'SENS',
  },
  {
    wire_id: 'W9',
    from_connector: 'J1',
    from_pin: '9',
    to_connector: 'J3',
    to_pin: '2',
    wire_color: 'white',
    gauge: '24 AWG',
    signal_name: 'SIG-',
    twist_group: 'SENS',
    shield_group: 'SENS',
  },
  {
    wire_id: 'W10',
    from_connector: 'J1',
    from_pin: '10',
    to_connector: 'J3',
    to_pin: '3',
    wire_color: 'bare',
    gauge: '24 AWG',
    signal_name: 'DRAIN',
    shield_group: 'SENS',
  },
]
